### ISSUE TITLE
Holding shift doesn't work with move command

### ISSUE THREAD

**Issue by ThibaultLemaire** [ThibaultLemaire/HomeworldSDL#13]
Making it impossible to move on the z axis (up/down) via the move command.

I fear that might have been a Linux fixme. Maybe I shouldn't have disabled fixmes altogether and focused on the one that was causing the game to occasionally segfault... (I know it has to do with Gun.c)

This is yet an other issue delaying the release of 1.0.0 because honestly that's a pretty hard impediment.

**Comment by ohemelaar** [comment]
I can't reproduce this issue. I have tested both with or without sensor mode, during the first mission, with scouts. I compiled from master just now (commit bd255e74d99d8420df416a26eb514d8c4af37bc4)

**Comment by ThibaultLemaire** [comment]
It's not really that it doesn't work, but rather it's really buggy. I had to keep spamming shift for it to go up/down, and it's snapping so you can't be precise.

As far as I can tell, it's an untainted compilation result, I made a new directory, ran `../configure` and `make`.


[screencast](https://ipfs.io/ipfs/QmS4Pfz3P38G6j3ktp9MFaejgaWyMKBq6nCLgDhXU2atUP)

**Comment by ohemelaar** [comment]
I can't view the screencast. GitHub show a page with the text
> Non-Image content-type returned
